# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_operations.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 806)
        MainWindow.setStyleSheet("QWidget{\n"
" background-color: rgb(255,246,233)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.question = QtWidgets.QLabel(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(129, 75, 691, 71))
        self.question.setStyleSheet("QLabel{background-color:rgb(73, 133, 168)}")
        self.question.setText("")
        self.question.setObjectName("question")
        self.answer_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.answer_1.setGeometry(QtCore.QRect(130, 190, 691, 41))
        self.answer_1.setStyleSheet("QRadioButton{background-color:rgb(255, 255, 255)}")
        self.answer_1.setText("")
        self.answer_1.setObjectName("answer_1")
        self.answer_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.answer_2.setGeometry(QtCore.QRect(130, 250, 691, 41))
        self.answer_2.setStyleSheet("QRadioButton{background-color:rgb(255, 255, 255)}")
        self.answer_2.setText("")
        self.answer_2.setObjectName("answer_2")
        self.answer_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.answer_3.setGeometry(QtCore.QRect(130, 310, 691, 41))
        self.answer_3.setStyleSheet("QRadioButton{background-color:rgb(255, 255, 255)}")
        self.answer_3.setText("")
        self.answer_3.setObjectName("answer_3")
        self.answer_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.answer_4.setGeometry(QtCore.QRect(130, 370, 691, 41))
        self.answer_4.setStyleSheet("QRadioButton{background-color:rgb(255, 255, 255)}")
        self.answer_4.setText("")
        self.answer_4.setObjectName("answer_4")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(130, 450, 113, 32))
        self.back_button.setStyleSheet("QPushButton{\n"
"background-color:rgb(73,133,168);\n"
"color:white;\n"
"\n"
"}")
        self.back_button.setObjectName("back_button")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(710, 450, 113, 32))
        self.next_button.setStyleSheet("QPushButton{\n"
"background-color:rgb(73,133,168);\n"
"color: white;\n"
"}")
        self.next_button.setObjectName("next_button")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(132, 20, 121, 32))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(73,133,168);\n"
"color:white;\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_button.setText(_translate("MainWindow", "Back"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.pushButton.setText(_translate("MainWindow", "Main Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
