# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practiceVennDiagram.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(875, 695)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: rgb(255,246,233)\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(73,133,168);\n"
"    color: white;\n"
"    font: 16pt \"Verdana\";\n"
"    border-radius: 20%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(93,153,168);\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QFrame{\n"
"    border:none;\n"
"}\n"
"\n"
"QLabel{\n"
"    font: Italic 22pt \"Verdana\";\n"
"    background-color: rgb(73, 133, 168);\n"
"    border-radius: 20%;\n"
"    color: white;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    font: 22pt;\n"
"}\n"
"\n"
"QCheckBox:hover{\n"
"    background-color: rgb(221,221,221);\n"
"    border-radius: 20%;\n"
"}\n"
"QCheckBox::indicator{\n"
"    width: 70px;\n"
"    height: 30px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"    image: url(/Users/adityaparashar/Education/UCL/ENGF0002/Scenario-2/checkbox-checked.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"    image: url(/Users/adityaparashar/Education/UCL/ENGF0002/Scenario-2/checkbox-unchecked.png);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.CheckboxFrame = QtWidgets.QFrame(self.centralwidget)
        self.CheckboxFrame.setGeometry(QtCore.QRect(20, 520, 871, 281))
        self.CheckboxFrame.setStyleSheet("")
        self.CheckboxFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CheckboxFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CheckboxFrame.setObjectName("CheckboxFrame")
        self.Area1 = QtWidgets.QCheckBox(self.CheckboxFrame)
        self.Area1.setEnabled(True)
        self.Area1.setGeometry(QtCore.QRect(80, 30, 121, 41))
        self.Area1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Area1.setAutoFillBackground(False)
        self.Area1.setStyleSheet("")
        self.Area1.setIconSize(QtCore.QSize(16, 16))
        self.Area1.setCheckable(True)
        self.Area1.setChecked(False)
        self.Area1.setTristate(False)
        self.Area1.setObjectName("Area1")
        self.Area2 = QtWidgets.QCheckBox(self.CheckboxFrame)
        self.Area2.setGeometry(QtCore.QRect(340, 30, 121, 41))
        self.Area2.setStyleSheet("")
        self.Area2.setObjectName("Area2")
        self.Area3 = QtWidgets.QCheckBox(self.CheckboxFrame)
        self.Area3.setGeometry(QtCore.QRect(600, 30, 131, 41))
        self.Area3.setObjectName("Area3")
        self.HiddenFrame = QtWidgets.QFrame(self.CheckboxFrame)
        self.HiddenFrame.setGeometry(QtCore.QRect(0, 80, 811, 171))
        self.HiddenFrame.setStyleSheet("border:none;")
        self.HiddenFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HiddenFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HiddenFrame.setObjectName("HiddenFrame")
        self.Area5 = QtWidgets.QCheckBox(self.HiddenFrame)
        self.Area5.setEnabled(True)
        self.Area5.setGeometry(QtCore.QRect(340, 30, 131, 41))
        self.Area5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Area5.setAutoFillBackground(False)
        self.Area5.setIconSize(QtCore.QSize(16, 16))
        self.Area5.setCheckable(True)
        self.Area5.setChecked(False)
        self.Area5.setTristate(False)
        self.Area5.setObjectName("Area5")
        self.Area4 = QtWidgets.QCheckBox(self.HiddenFrame)
        self.Area4.setEnabled(True)
        self.Area4.setGeometry(QtCore.QRect(80, 30, 121, 41))
        self.Area4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Area4.setAutoFillBackground(False)
        self.Area4.setIconSize(QtCore.QSize(16, 16))
        self.Area4.setCheckable(True)
        self.Area4.setChecked(False)
        self.Area4.setTristate(False)
        self.Area4.setObjectName("Area4")
        self.Area7 = QtWidgets.QCheckBox(self.HiddenFrame)
        self.Area7.setEnabled(True)
        self.Area7.setGeometry(QtCore.QRect(340, 110, 141, 41))
        self.Area7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Area7.setAutoFillBackground(False)
        self.Area7.setIconSize(QtCore.QSize(16, 16))
        self.Area7.setCheckable(True)
        self.Area7.setChecked(False)
        self.Area7.setTristate(False)
        self.Area7.setObjectName("Area7")
        self.Area6 = QtWidgets.QCheckBox(self.HiddenFrame)
        self.Area6.setEnabled(True)
        self.Area6.setGeometry(QtCore.QRect(600, 30, 131, 41))
        self.Area6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Area6.setAutoFillBackground(False)
        self.Area6.setIconSize(QtCore.QSize(16, 16))
        self.Area6.setCheckable(True)
        self.Area6.setChecked(False)
        self.Area6.setTristate(False)
        self.Area6.setObjectName("Area6")
        self.QuestionFrame = QtWidgets.QFrame(self.centralwidget)
        self.QuestionFrame.setGeometry(QtCore.QRect(20, 410, 1401, 101))
        self.QuestionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QuestionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QuestionFrame.setObjectName("QuestionFrame")
        self.Question = QtWidgets.QLabel(self.QuestionFrame)
        self.Question.setGeometry(QtCore.QRect(0, 0, 1391, 101))
        self.Question.setStyleSheet("")
        self.Question.setObjectName("Question")
        self.DiagramFrame = QtWidgets.QFrame(self.centralwidget)
        self.DiagramFrame.setGeometry(QtCore.QRect(20, 0, 721, 401))
        self.DiagramFrame.setStyleSheet("")
        self.DiagramFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DiagramFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DiagramFrame.setObjectName("DiagramFrame")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(1100, 790, 121, 46))
        self.submitButton.setStyleSheet("")
        self.submitButton.setObjectName("submitButton")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(1250, 790, 121, 46))
        self.nextButton.setObjectName("nextButton")
        self.QuestionFrame.raise_()
        self.DiagramFrame.raise_()
        self.CheckboxFrame.raise_()
        self.submitButton.raise_()
        self.nextButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Area1.setText(_translate("MainWindow", "1"))
        self.Area2.setText(_translate("MainWindow", "2"))
        self.Area3.setText(_translate("MainWindow", "3"))
        self.Area5.setText(_translate("MainWindow", "5"))
        self.Area4.setText(_translate("MainWindow", "4"))
        self.Area7.setText(_translate("MainWindow", "7"))
        self.Area6.setText(_translate("MainWindow", "6"))
        self.Question.setText(_translate("MainWindow", "<html><head/><body><p>&nbsp; &nbsp; Shade the given area: (A&amp;B)</p></body></html>"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.nextButton.setText(_translate("MainWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
