# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1438, 806)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: rgb(255,246,233);\n"
"}\n"
"\n"
"#header{\n"
"    font: 90pt \"Baloo Bhaijaan\";\n"
"    background-color: rgb(73,133,168);\n"
"    color: white;\n"
"    border-radius: 30%;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(73,133,168);\n"
"    color: white;\n"
"    font: 25pt \"Verdana\";\n"
"    border-radius: 20%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(93,153,168);\n"
"    border: 2px solid black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(0, 0, 1431, 251))
        self.header.setStyleSheet("")
        self.header.setObjectName("header")
        self.practiceButton = QtWidgets.QPushButton(self.centralwidget)
        self.practiceButton.setGeometry(QtCore.QRect(520, 360, 421, 131))
        self.practiceButton.setObjectName("practiceButton")
        self.createButton = QtWidgets.QPushButton(self.centralwidget)
        self.createButton.setGeometry(QtCore.QRect(520, 620, 421, 131))
        self.createButton.setObjectName("createButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 750, 271, 211))
        self.label.setStyleSheet("border: 5px solid rgb(73,133,168);\n"
"padding: 10px;\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1120, 290, 301, 171))
        self.label_4.setStyleSheet("padding: 10%;\n"
"background-color: rgb(73,133,168);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("img3.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">INTERACTIVE SET-THEORY</p></body></html>"))
        self.practiceButton.setText(_translate("MainWindow", "Practice Exercises"))
        self.createButton.setText(_translate("MainWindow", "Create Exercises"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
