# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practice_laws.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1437, 775)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 246, 233);\n"
"    font-family: \"Verdana\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(73,133,168);\n"
"    border-radius: 20%;\n"
"    color: white;\n"
"    font-size: 16pt;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(93,153,168);\n"
"    border: 2px solid rgb(53, 54, 90);\n"
"}\n"
"       \n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(1230, 690, 111, 51))
        self.next_button.setStyleSheet("")
        self.next_button.setObjectName("next_button")
        self.main_menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.main_menu_button.setGeometry(QtCore.QRect(60, 690, 131, 51))
        self.main_menu_button.setStyleSheet("")
        self.main_menu_button.setObjectName("main_menu_button")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(40, 30, 1331, 101))
        self.header.setStyleSheet("#header{\n"
"    font-weight: bold;\n"
"    font-size: 70pt;\n"
"    text-align: center;\n"
"    color: black;\n"
"}")
        self.header.setObjectName("header")
        self.questionFrame = QtWidgets.QFrame(self.centralwidget)
        self.questionFrame.setGeometry(QtCore.QRect(220, 140, 971, 621))
        self.questionFrame.setStyleSheet("QFrame{border:none;\n"
"background-color: rgb(73,133,168);\n"
"border-radius: 20%;}\n"
"\n"
"QFrame::hover{\n"
"    background-color: white;\n"
"}")
        self.questionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.questionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.questionFrame.setObjectName("questionFrame")
        self.Question_label = QtWidgets.QLabel(self.questionFrame)
        self.Question_label.setGeometry(QtCore.QRect(0, 0, 971, 621))
        self.Question_label.setStyleSheet("#Question_label{\n"
"    font-style: italic;\n"
"    font-size: 28pt;\n"
"    color: white;\n"
"    border-radius: 20%;\n"
"    padding-top: 15%;\n"
"}\n"
"\n"
"#Question_label::hover{\n"
"    background-color:transparent;\n"
"    color: black;\n"
"}")
        self.Question_label.setTextFormat(QtCore.Qt.RichText)
        self.Question_label.setScaledContents(True)
        self.Question_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Question_label.setObjectName("Question_label")
        self.Answer_label = QtWidgets.QLabel(self.questionFrame)
        self.Answer_label.setGeometry(QtCore.QRect(20, 130, 901, 61))
        self.Answer_label.setStyleSheet("#Answer_label{\n"
"    background-color: white;\n"
"    border-radius: 20%;\n"
"    font-family: \"Calibri\";\n"
"    font-weight: 900;\n"
"    font-size:32pt; \n"
"}")
        self.Answer_label.setTextFormat(QtCore.Qt.RichText)
        self.Answer_label.setScaledContents(True)
        self.Answer_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Answer_label.setObjectName("Answer_label")
        self.Image_label = QtWidgets.QLabel(self.questionFrame)
        self.Image_label.setGeometry(QtCore.QRect(20, 220, 901, 391))
        self.Image_label.setStyleSheet("")
        self.Image_label.setText("")
        self.Image_label.setPixmap(QtGui.QPixmap("../practice_laws/resources/DM2.png"))
        self.Image_label.setScaledContents(True)
        self.Image_label.setObjectName("Image_label")
        self.Answer_label.raise_()
        self.Image_label.raise_()
        self.Question_label.raise_()
        self.next_button.raise_()
        self.header.raise_()
        self.main_menu_button.raise_()
        self.questionFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.main_menu_button.setText(_translate("MainWindow", "Main Menu"))
        self.header.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">FUNDAMENTAL SET LAWS</p></body></html>"))
        self.Question_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">According to de-morgan law:</p><p align=\"center\">(A ∩ B)’ = ??? </p></body></html>"))
        self.Answer_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">A' U B'</p></body></html>"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
