# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectPracticeQn.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 806)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color:rgb(255,246,233);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 23pt \'Verdana\';\n"
"background-color:rgb(73,133,168);\n"
"border-radius:25%;\n"
"color:white}\n"
"\n"
"QPushButton:Hover{\n"
"background-color:rgb(93,153,168);\n"
"border:3px solid black;\n"
"}\n"
"\n"
"#HomeButton{\n"
"font: 20pt \'Verdana\';\n"
"background-color:rgb(73,133,168);\n"
"border-radius:30%;\n"
"color:white;}\n"
"\n"
"#HomeButton:Hover{\n"
"background-color:rgb(93,153,168);\n"
"border:2px solid black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SetOperations = QtWidgets.QPushButton(self.centralwidget)
        self.SetOperations.setGeometry(QtCore.QRect(510, 300, 431, 91))
        self.SetOperations.setStyleSheet("")
        self.SetOperations.setObjectName("SetOperations")
        self.TeacherSheets = QtWidgets.QPushButton(self.centralwidget)
        self.TeacherSheets.setGeometry(QtCore.QRect(510, 130, 431, 91))
        self.TeacherSheets.setStyleSheet("")
        self.TeacherSheets.setObjectName("TeacherSheets")
        self.SetLaws = QtWidgets.QPushButton(self.centralwidget)
        self.SetLaws.setGeometry(QtCore.QRect(510, 470, 431, 91))
        self.SetLaws.setStyleSheet("")
        self.SetLaws.setObjectName("SetLaws")
        self.VennDiagrams = QtWidgets.QPushButton(self.centralwidget)
        self.VennDiagrams.setGeometry(QtCore.QRect(510, 640, 431, 91))
        self.VennDiagrams.setStyleSheet("")
        self.VennDiagrams.setObjectName("VennDiagrams")
        self.HomeButton = QtWidgets.QPushButton(self.centralwidget)
        self.HomeButton.setGeometry(QtCore.QRect(60, 40, 171, 71))
        self.HomeButton.setStyleSheet("")
        self.HomeButton.setObjectName("HomeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SetOperations.setText(_translate("MainWindow", "Practice Set Operations"))
        self.TeacherSheets.setText(_translate("MainWindow", "Load Teacher Exercises"))
        self.SetLaws.setText(_translate("MainWindow", "Practice Set Laws"))
        self.VennDiagrams.setText(_translate("MainWindow", "Shade Venn Diagrams"))
        self.HomeButton.setText(_translate("MainWindow", "Main Menu"))