# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Code/Create_Exercises/src/files_ui/CreateExercisesQn.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1438, 806)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color:rgb(255,246,233);\n"
"}\n"
"\n"
"QTextEdit{\n"
"    background-color: white;\n"
"    border-radius: 25%;\n"
"    border: 1px solid black;    \n"
"    font: 20pt \"Verdana\";\n"
"}\n"
"\n"
"#noOfSets{\n"
"    font: bold 17pt;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(73, 133, 168);\n"
"    color: white;    \n"
"    border-radius: 20%;\n"
"    font: 22pt \"Verdana\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(93,153, 168);\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"#A, #AND, #B, #C, #OR, #compliment, #minus{\n"
"    border-radius: 10%;\n"
"    font-size: 20pt;\n"
"}\n"
"\n"
"#frame, #frame_2{\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QLabel{\n"
"color:white;\n"
"background-color:rgb(73,133,168);\n"
"font:Italic 22pt \'Verdana\';\n"
"border-radius:20%;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    font: 20pt;\n"
"}\n"
"QRadioButton:indicator{\n"
"    width: 50px;\n"
"    height: 20px;    \n"
"}\n"
"\n"
"QRadioButton:indicator::checked{\n"
"    image: url(../Create_Exercises/src/files_ui/radio-checked.png)\n"
"}\n"
"\n"
"QRadioButton:indicator::unchecked{\n"
"    image: url(../Create_Exercises/src/files_ui/radio-unchecked.png)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 411, 821))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.A = QtWidgets.QPushButton(self.frame)
        self.A.setGeometry(QtCore.QRect(100, 400, 62, 45))
        self.A.setStyleSheet("")
        self.A.setObjectName("A")
        self.B = QtWidgets.QPushButton(self.frame)
        self.B.setGeometry(QtCore.QRect(190, 400, 62, 45))
        self.B.setStyleSheet("")
        self.B.setObjectName("B")
        self.C = QtWidgets.QPushButton(self.frame)
        self.C.setGeometry(QtCore.QRect(100, 480, 62, 45))
        self.C.setStyleSheet("")
        self.C.setObjectName("C")
        self.AND = QtWidgets.QPushButton(self.frame)
        self.AND.setGeometry(QtCore.QRect(190, 480, 62, 45))
        self.AND.setStyleSheet("")
        self.AND.setObjectName("AND")
        self.OR = QtWidgets.QPushButton(self.frame)
        self.OR.setGeometry(QtCore.QRect(100, 560, 62, 45))
        self.OR.setStyleSheet("QPushButton\n"
"{\n"
"font:20pt;\n"
"border-radius: 10%;\n"
"}")
        self.OR.setObjectName("OR")
        self.minus = QtWidgets.QPushButton(self.frame)
        self.minus.setGeometry(QtCore.QRect(190, 560, 62, 45))
        self.minus.setStyleSheet("")
        self.minus.setObjectName("minus")
        self.compliment = QtWidgets.QPushButton(self.frame)
        self.compliment.setGeometry(QtCore.QRect(100, 640, 62, 50))
        self.compliment.setStyleSheet("")
        self.compliment.setObjectName("compliment")
        self.setElem_2 = QtWidgets.QLabel(self.frame)
        self.setElem_2.setGeometry(QtCore.QRect(50, 690, 301, 61))
        self.setElem_2.setStyleSheet("font: 15pt \"Calibri\";\n"
"color: rgb(188, 48, 56);\n"
"background-color: transparent;")
        self.setElem_2.setAlignment(QtCore.Qt.AlignCenter)
        self.setElem_2.setObjectName("setElem_2")
        self.setEqn = QtWidgets.QLabel(self.centralwidget)
        self.setEqn.setGeometry(QtCore.QRect(580, 40, 511, 81))
        self.setEqn.setStyleSheet("")
        self.setEqn.setObjectName("setEqn")
        self.eqn_input = QtWidgets.QTextEdit(self.centralwidget)
        self.eqn_input.setGeometry(QtCore.QRect(600, 140, 461, 61))
        self.eqn_input.setStyleSheet("")
        self.eqn_input.setObjectName("eqn_input")
        self.setElem = QtWidgets.QLabel(self.centralwidget)
        self.setElem.setGeometry(QtCore.QRect(600, 260, 471, 61))
        self.setElem.setStyleSheet("")
        self.setElem.setObjectName("setElem")
        self.elem_input1 = QtWidgets.QTextEdit(self.centralwidget)
        self.elem_input1.setGeometry(QtCore.QRect(600, 350, 371, 51))
        self.elem_input1.setStyleSheet("")
        self.elem_input1.setObjectName("elem_input1")
        self.elem_input2 = QtWidgets.QTextEdit(self.centralwidget)
        self.elem_input2.setGeometry(QtCore.QRect(600, 440, 371, 51))
        self.elem_input2.setStyleSheet("")
        self.elem_input2.setObjectName("elem_input2")
        self.elem_input3 = QtWidgets.QTextEdit(self.centralwidget)
        self.elem_input3.setGeometry(QtCore.QRect(600, 530, 371, 51))
        self.elem_input3.setStyleSheet("")
        self.elem_input3.setObjectName("elem_input3")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(1210, 670, 151, 61))
        self.submitButton.setStyleSheet("")
        self.submitButton.setObjectName("submitButton")
        self.finishButton = QtWidgets.QPushButton(self.centralwidget)
        self.finishButton.setGeometry(QtCore.QRect(1010, 670, 161, 61))
        self.finishButton.setStyleSheet("")
        self.finishButton.setObjectName("finishButton")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, -10, 411, 341))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.noOfSets = QtWidgets.QLabel(self.frame_2)
        self.noOfSets.setGeometry(QtCore.QRect(80, 110, 231, 61))
        self.noOfSets.setStyleSheet("")
        self.noOfSets.setObjectName("noOfSets")
        self.no2 = QtWidgets.QRadioButton(self.frame_2)
        self.no2.setGeometry(QtCore.QRect(100, 190, 100, 41))
        self.no2.setStyleSheet("")
        self.no2.setObjectName("no2")
        self.no3 = QtWidgets.QRadioButton(self.frame_2)
        self.no3.setGeometry(QtCore.QRect(100, 240, 101, 41))
        self.no3.setStyleSheet("")
        self.no3.setObjectName("no3")
        self.homeButton = QtWidgets.QPushButton(self.frame_2)
        self.homeButton.setGeometry(QtCore.QRect(20, 20, 151, 51))
        self.homeButton.setStyleSheet("")
        self.homeButton.setObjectName("homeButton")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(1100, 150, 291, 41))
        self.errorLabel.setStyleSheet("background-color:rgb(255,246,233);\n"
"color:red")
        self.errorLabel.setObjectName("errorLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(510, 350, 61, 51))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 440, 61, 51))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(510, 530, 61, 51))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.A.setText(_translate("MainWindow", "A"))
        self.B.setText(_translate("MainWindow", "B"))
        self.C.setText(_translate("MainWindow", "C"))
        self.AND.setText(_translate("MainWindow", "∩"))
        self.OR.setText(_translate("MainWindow", "U"))
        self.minus.setText(_translate("MainWindow", "\\"))
        self.compliment.setText(_translate("MainWindow", "\'"))
        self.setElem_2.setText(_translate("MainWindow", "Only these values allowed !!!"))
        self.setEqn.setText(_translate("MainWindow", "      Enter Equation for Set Operation"))
        self.setElem.setText(_translate("MainWindow", "       Enter Set Elements"))
        self.submitButton.setText(_translate("MainWindow", "Next"))
        self.finishButton.setText(_translate("MainWindow", "Finish"))
        self.noOfSets.setText(_translate("MainWindow", "  Select Number of Sets"))
        self.no2.setText(_translate("MainWindow", "2"))
        self.no3.setText(_translate("MainWindow", "3"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.errorLabel.setText(_translate("MainWindow", "Please Enter Valid Values!"))
        self.label.setText(_translate("MainWindow", "A"))
        self.label_2.setText(_translate("MainWindow", "B"))
        self.label_3.setText(_translate("MainWindow", "C"))
