# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadQn.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1438, 806)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color:rgba(255,246,233,168);\n"
"}\n"
"\n"
"#answerInput{\n"
"    background-color:white;\n"
"    border-radius: 20%;\n"
"    border: 1px solid black;\n"
"    font: 22pt \"Verdana\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:rgb(73,133,168);\n"
"    color: white;\n"
"    font: 20pt \"Verdana\";\n"
"    border-radius: 25%;\n"
"}\n"
"\n"
"#label_7, #eqn_input{\n"
"    background-color: rgb(73,133,168);\n"
"    color: white;\n"
"    border-radius: 20%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(93,153,168);\n"
"    border: 2px solid black;\n"
"}\n"
"#instructionLabel{\n"
"    font:Italic 22pt \"Verdana\";\n"
"}\n"
"\n"
"QLabel{\n"
"    font: italic 26pt \"Verdana\";\n"
"    color: black;\n"
"}\n"
"")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.answerInput = QtWidgets.QTextEdit(self.centralwidget)
        self.answerInput.setGeometry(QtCore.QRect(490, 460, 511, 71))
        self.answerInput.setStyleSheet("")
        self.answerInput.setObjectName("answerInput")
        self.instructionLabel = QtWidgets.QLabel(self.centralwidget)
        self.instructionLabel.setGeometry(QtCore.QRect(550, 390, 421, 71))
        self.instructionLabel.setStyleSheet("")
        self.instructionLabel.setObjectName("instructionLabel")
        self.doneButton = QtWidgets.QPushButton(self.centralwidget)
        self.doneButton.setGeometry(QtCore.QRect(620, 660, 191, 61))
        self.doneButton.setStyleSheet("")
        self.doneButton.setObjectName("doneButton")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(100, 660, 151, 61))
        self.backButton.setStyleSheet("")
        self.backButton.setObjectName("backButton")
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(10, 10, 201, 61))
        self.homeButton.setStyleSheet("")
        self.homeButton.setObjectName("homeButton")
        self.eqn_input = QtWidgets.QLabel(self.centralwidget)
        self.eqn_input.setGeometry(QtCore.QRect(725, 290, 171, 71))
        self.eqn_input.setStyleSheet("")
        self.eqn_input.setObjectName("eqn_input")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 290, 211, 71))
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.elem_input1 = QtWidgets.QLabel(self.centralwidget)
        self.elem_input1.setGeometry(QtCore.QRect(130, 80, 159, 71))
        self.elem_input1.setStyleSheet("")
        self.elem_input1.setObjectName("elem_input1")
        self.a = QtWidgets.QLabel(self.centralwidget)
        self.a.setGeometry(QtCore.QRect(60, 80, 71, 71))
        self.a.setStyleSheet("")
        self.a.setObjectName("a")
        self.b = QtWidgets.QLabel(self.centralwidget)
        self.b.setGeometry(QtCore.QRect(60, 130, 51, 71))
        self.b.setStyleSheet("")
        self.b.setObjectName("b")
        self.elem_input2 = QtWidgets.QLabel(self.centralwidget)
        self.elem_input2.setGeometry(QtCore.QRect(130, 130, 151, 71))
        self.elem_input2.setStyleSheet("")
        self.elem_input2.setObjectName("elem_input2")
        self.c = QtWidgets.QLabel(self.centralwidget)
        self.c.setGeometry(QtCore.QRect(60, 190, 51, 61))
        self.c.setStyleSheet("")
        self.c.setObjectName("c")
        self.elem_input3 = QtWidgets.QLabel(self.centralwidget)
        self.elem_input3.setGeometry(QtCore.QRect(130, 180, 151, 81))
        self.elem_input3.setStyleSheet("")
        self.elem_input3.setObjectName("elem_input3")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(1110, 660, 191, 61))
        self.nextButton.setStyleSheet("")
        self.nextButton.setObjectName("nextButton")
        self.answerInput.raise_()
        self.instructionLabel.raise_()
        self.doneButton.raise_()
        self.backButton.raise_()
        self.homeButton.raise_()
        self.label_7.raise_()
        self.elem_input1.raise_()
        self.a.raise_()
        self.b.raise_()
        self.elem_input2.raise_()
        self.c.raise_()
        self.elem_input3.raise_()
        self.nextButton.raise_()
        self.eqn_input.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionView = QtWidgets.QAction(MainWindow)
        self.actionView.setObjectName("actionView")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.answerInput.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:22pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>"))
        self.instructionLabel.setText(_translate("MainWindow", " Please Enter your Answer Below:"))
        self.doneButton.setText(_translate("MainWindow", "FINISH"))
        self.backButton.setText(_translate("MainWindow", "BACK"))
        self.homeButton.setText(_translate("MainWindow", "HOME"))
        self.eqn_input.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>&nbsp; &nbsp; What is:</p></body></html>"))
        self.elem_input1.setText(_translate("MainWindow", "TextLabel"))
        self.a.setText(_translate("MainWindow", "A ="))
        self.b.setText(_translate("MainWindow", "B ="))
        self.elem_input2.setText(_translate("MainWindow", "TextLabel"))
        self.c.setText(_translate("MainWindow", "C ="))
        self.elem_input3.setText(_translate("MainWindow", "TextLabel"))
        self.nextButton.setText(_translate("MainWindow", "NEXT"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionView.setText(_translate("MainWindow", "View"))
