# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Code/ScoreDisplay/scoreDisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 806)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: rgb(255,246,233);\n"
"}\n"
"\n"
"#resultLabel{\n"
"    background-color: rgb(73,133,168);\n"
"    border-radius: 40%;\n"
"    color: white;\n"
"    font: 50pt \"Verdana\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(73,133,168);\n"
"    border-radius: 20%;\n"
"    color: white;\n"
"    font: 20pt \"Verdana\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(93,153,168);\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 80pt \"Calibri\";\n"
"    font-weight: 900;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(300, 200, 921, 391))
        self.resultLabel.setObjectName("resultLabel")
        self.Header = QtWidgets.QLabel(self.centralwidget)
        self.Header.setGeometry(QtCore.QRect(270, 50, 981, 121))
        self.Header.setObjectName("Header")
        self.mainMenu_Button = QtWidgets.QPushButton(self.centralwidget)
        self.mainMenu_Button.setGeometry(QtCore.QRect(20, 20, 191, 61))
        self.mainMenu_Button.setObjectName("mainMenu_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.resultLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.Header.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">FINAL SCORE</p></body></html>"))
        self.mainMenu_Button.setText(_translate("MainWindow", "Main Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
