# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 806)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: rgb(255,246,233);\n"
"}\n"
"\n"
"#header{\n"
"    font: 90pt \"Baloo Bhaijaan\";\n"
"    background-color: rgb(73,133,168);\n"
"    color: white;\n"
"    border-radius: 70%;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(73,133,168);\n"
"    color: white;\n"
"    font: 25pt \"Verdana\";\n"
"    border-radius: 20%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(93,153,168);\n"
"    border: 2px solid black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(0, 0, 1431, 251))
        self.header.setStyleSheet("")
        self.header.setObjectName("header")
        self.practiceButton = QtWidgets.QPushButton(self.centralwidget)
        self.practiceButton.setGeometry(QtCore.QRect(520, 360, 421, 131))
        self.practiceButton.setObjectName("practiceButton")
        self.createButton = QtWidgets.QPushButton(self.centralwidget)
        self.createButton.setGeometry(QtCore.QRect(520, 620, 421, 131))
        self.createButton.setObjectName("createButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">INTERACTIVE SET-THEORY</p></body></html>"))
        self.practiceButton.setText(_translate("MainWindow", "Practice Exercises"))
        self.createButton.setText(_translate("MainWindow", "Create Exercises"))

